export const routes = {
  home: '/',
  login: '/login',
  signup: '/signup',
  invite: '/invite',
  createProfile: '/create-profile',
  profilePreview: '/profile-preview',
  paywall: '/paywall',
  authCallback: '/auth/callback',
  vault: '/vault',
  inbox: '/inbox',
  myBlackbook: '/my-blackbook',
  editProfile: '/edit-profile',
  contact: (id: string) => `/contact/${id}`,
  publicProfile: (username: string) => `/p/${username}?from=app`,
  share: '/share',
  creativeDirector: '/creative-director',
  photographerBeige: '/photographer-beige',
  ecommerceSpecialist: '/ecommerce-specialist',
  saveConfirmation: '/save-confirmation',
  previewTemplateVisual: '/preview-template/visual',
  previewTemplateEditorial: '/preview-template/editorial',
  requestAccess: '/request-access',
  requestAccessStatus: (id: string) => `/request-access/status?id=${id}`,
  adminRequests: '/admin/requests',
  adminResetProfile: '/admin/reset-profile',
  adminUsers: '/admin/users',
  adminUserCreate: '/admin/users/new',
  adminUserEdit: (id: string) => `/admin/users/${id}/edit`,
  vcardDownload: (username: string) => `/api/vcard/${username}`,
  walletPass: (username: string) => `/api/wallet/pass/${username}`,
  onboarding: '/onboarding',
  settings: '/settings',
  scanQr: '/scan-qr',
  scanCard: '/scan-card',
} as const;
