export const routes = {
  home: '/',
  login: '/login',
  signup: '/signup',
  invite: '/invite',
  createProfile: '/create-profile',
  profilePreview: '/profile-preview',
  paywall: '/paywall',
  authCallback: '/auth/callback',
  vault: '/vault',
  myBlackbook: '/my-blackbook',
  editProfile: '/edit-profile',
  contact: (id: string) => `/contact/${id}`,
  publicProfile: (username: string) => `/p/${username}`,
  share: '/share',
  creativeDirector: '/creative-director',
  photographerBeige: '/photographer-beige',
  ecommerceSpecialist: '/ecommerce-specialist',
  saveConfirmation: '/save-confirmation',
  previewTemplateVisual: '/preview-template/visual',
  previewTemplateEditorial: '/preview-template/editorial',
  requestAccess: '/request-access',
  requestAccessPending: '/request-access/pending',
  adminRequests: '/admin/requests',
} as const;
